### ISSUE TITLE
Open Data Policy?

### ISSUE THREAD

**Issue by waldoj** [mheadd/communitydata.io#7]
What's with the `Open Data Policy?` column in [communityopendatacatalogs.csv](https://github.com/mheadd/communitydata.io/blob/master/communityopendatacatalogs.csv)? I'm not sure what it would mean for a community repo to have an open data policy.

**Comment by mheadd** [comment]
Good point.

That list was extracted from [another that was created by Sunlight Foundation](https://github.com/sunlightpolicy/opendata/blob/master/USlocalopendataportals.csv), and I think that column was part of the original list - probably not meaningful in this context.

/cc: @rebeccawilliams

**Comment by rebeccawilliams** [comment]
Yup, that's the background. It's a reference to government policies, that like population, seemed like helpful context to not delete when porting the list over.
